### PR TITLE
Update For The Chop Shop 3095 DLC

### PR DESCRIPTION
**Pull request by TayMcKenzieNZ**
- Updated Prop / Object List to latest DLC

- Updated and added all ped models in the pedlist.xml file, also renamed some such as Ary = Dr Dre, Juan Strickler / El Rubio, mjo / DJ Pooh

- Removed MP Male and MP Female from Multiplayer category as already present in Player category

- Removed Michael, Trevor Franklin from Story category as already present in Player category

- Updated the animation list to a file I had previously. It is not up to the latest DLC however has a ton of animations that are not present in MAFINS or ItJustCurtis' version. I believe it's up to Drug War or San Andreas Mercenaries

### CODE REVIEW

**Comment by TayMcKenzieNZ** [comment]
I don't know anything about C, C++ or whatever but updated the Ped Anim List, Ped List and Prop List 😀

**Comment by TayMcKenzieNZ** [comment]
Shit, looks like I made a mistake in the PedList as they're appearing empty 😬

**Comment by TayMcKenzieNZ** [comment]
Crap, I'm really sorry! All the other files are fine but the PedList one is broken and I can't for the life of me figure out why 😭

**Comment by itsjustcurtis** [comment]
Merging into the Patch branch, I'll do some local tests with this and figure out what has broken. In future I would like these lists to be dynamically generated like the vehicles.

**Comment by TayMcKenzieNZ** [comment]
I may have fixed the problem; there was some missing closures and I had changed Animal to Animals. It should in theory be fixed now

**Comment by itsjustcurtis** [comment]
Ahh perfect, if you can send a new PR with your changes, I can merge them in

**Comment by TayMcKenzieNZ** [comment]
Tested and working as intended. New PR made :)

**Pull request merged**
