### PR TITLE
Add Outfit Auto Load

### PR DESCRIPTION
**Pull request by Hydraxonn**
Automatically load and apply menyooStuff/defaultPed.xml on startup. Minimal changes, does not crash if the XML file isn't present.

### CODE REVIEW

**Comment by itsjustcurtis** [comment]
Is it worth adding the defaultped.xml file as well to make it easier for users? Or is that something that Menyoo will create once a default has been set within the menu system?  

Also, is there a valid reason to have put this in the Loops subroutine? This segment of code will be running constantly as soon as menyoo is loaded, I worry this will have a significant performance hit.

**Comment by itsjustcurtis** [comment]
Also, please ensure to branch from and merge to the development branches, not main

**Comment by Hydraxonn** [comment]
>Also, please ensure to branch from and merge to the development branches, not main

Of course, my mistake, sorry. Still figuring out how PRs work.

>Is it worth adding the defaultped.xml file as well to make it easier for users? Or is that something that Menyoo will create once a default has been set within the menu system?

Right now it just loads the file if it exists, and doesn't if it doesn't. I can see about adding a keybind in the Outfits menu that will set the highlighted outfit as default by copying it to the location.

>Also, is there a valid reason to have put this in the Loops subroutine? This segment of code will be running constantly as soon as menyoo is loaded, I worry this will have a significant performance hit.

I tried placing the code in the initial load area just above the loops function, but I couldn't get it to reliably load every time with different game load durations. Using the defaultPedSet bool makes it so the setting of the outfit only runs once, so it should have minimal performance impact since it just checks a false value and does nothing. I also had the code running correctly in the JustOpened function, but I wanted the outfit auto-load to work whether or not the player has opened the menu.

That being said, if there's another place in the code where I can reliably run this, just once, just after the game loads, I'd be happy to move it.

**Comment by itsjustcurtis** [comment]
That all sounds well thought out. I'll merge it in now, testers can identify if it causes a problem, I can always optimise the code at a later date if need be.

**Pull request merged**
